"""
config.py — Single source of truth for the democratic topic modeling pipeline.

Every default here matches the reference implementation reported in:
Thomas (2026), "Coherence-Optimized Topic Modeling with Democratic Large
Language Model Interpretation." Change values here, not in the stage scripts,
so a run remains auditable from one file.
"""

from dataclasses import dataclass, field


@dataclass
class PipelineConfig:
    # ----- I/O ---------------------------------------------------------------
    input_csv: str = "tweet_data.csv"          # must contain a 'tweet' column
    output_dir: str = "pipeline_output"        # all stage artifacts land here
    stopwords_file: str = "custom_stopwords.txt"  # comma-separated domain stopwords

    # ----- Stage 1: coherence-optimized topic discovery ---------------------
    embedding_model: str = "all-MiniLM-L6-v2"  # SentenceTransformer model
    search_iterations: int = 50                # random hyperparameter draws
    topic_min: int = 2                         # max-topic solutions evaluated:
    topic_max: int = 25                        # range(topic_min, topic_max + 1)
    random_seed: int = 42                      # seeds the search; log with results
    save_visualizations: bool = False          # per-iteration HTML (heavy; final model always saved)

    # UMAP / HDBSCAN sampling spaces (identical to the reference implementation)
    umap_space: dict = field(default_factory=lambda: {
        "n_neighbors": [5, 10, 15, 20, 25, 30, 35],
        "n_components": [3, 4, 5, 6, 7, 8, 9, 10],
        "min_dist": [0.01, 0.05, 0.1, 0.5],
        "metric": ["cosine"],
    })
    hdbscan_space: dict = field(default_factory=lambda: {
        "min_cluster_size": [5, 10, 15, 20, 25, 30, 35],
        "metric": ["euclidean"],
        "cluster_selection_method": ["eom"],
    })

    # ----- Stages 2 & 4: LLM settings ---------------------------------------
    llm_model: str = "gpt-4o"                  # pin and report the identifier
    domain_context: str = (
        "tweets generated by alcohol companies during the COVID-19 pandemic"
    )                                          # the ONLY domain-specific prompt text

    # Stage 2: democratic naming
    votes_per_topic: int = 5000                # reference implementation value
    naming_temperature: float = 0.5
    naming_max_tokens: int = 15
    early_stop: bool = False                   # optional cost control:
    early_stop_window: int = 500               # stop if modal label share is stable
    early_stop_share: float = 0.60             # across this window at >= this share
    max_retries: int = 5                       # exponential backoff on API errors

    # Stage 4: corpus-scale classification
    themes: list = field(default_factory=lambda: [
        "Alcohol Delivery and Isolation Drinking",
        "Restaurant Support",
        "Social Media Promotions",
        "Sports",
        "Gaming",
    ])
    none_label: str = "The text does not fit into any of these themes"
    classify_temperature: float = 0.5
    classify_max_tokens: int = 30
    benchmark_csv: str = "human_labels.csv"    # columns: tweet, human_label (n=250)
    agreement_threshold: float = 0.85          # do not scale below this

    # ----- Stage 5: inference ------------------------------------------------
    # Period boundaries for proportional z-tests (inclusive, YYYY-MM-DD).
    # Requires a 'date' column in the input CSV.
    periods: dict = field(default_factory=lambda: {
        "pre":  ("2019-01-01", "2020-01-31"),
        "peri": ("2020-03-01", "2020-05-31"),
        "post": ("2020-06-01", "2021-07-31"),
    })
    alpha: float = 0.05                        # Bonferroni-corrected in stage 5


CONFIG = PipelineConfig()
